quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=denis
quarkus.datasource.password=denis
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/avgustovski
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.http.port=8082
%test.quarkus.http.port=8083
quarkus.rest-client.geonames-client.url=https://api.3geonames.org
quarkus.rest-client.openmeteo-client.url=https://api.open-meteo.com